language: node_js

sudo: false

node_js:
- node
- 11
- 10
- 9

jobs:
  include:
    - stage: build
      script:
      - npm run build
    - stage: lint
      script:
      - npm run lint
    - stage: test
      script:
      - npm test
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release


