export enum Permission {
    AgeGroupsRead = "age-groups:read",
    AgeGroupsWrite = "age-groups:write",
    ChildAttendanceRead = "child-attendance:read",
    ChildAttendanceWrite = "child-attendance:write",
    ChildRead = "child:read",
    ChildWrite = "child:write",
    ContactPersonRead = "contact-person:read",
    ContactPersonWrite = "contact-person:write",
    CrewAttendanceRead = "crew-attendance:read",
    CrewAttendanceWrite = "crew-attendance:write",
    CrewMemberRead = "crew-member:read",
    CrewMemberWrite = "crew-member:write",
    DiscountRead = "discounts:read",
    DiscountsWrite = "discounts:write",
    ReportsDelete = "reports:delete",
    ReportsRead = "reports:read",
    ReportsRequest = "reports:request",
    ShiftPresetRead = "shift-preset:read",
    ShiftPresetWrite = "shift-preset:write",
    ShiftRead = "shift:read",
    ShiftWrite = "shift:write",
    TemplateFillIn = "template:fill-in",
    TemplateRead = "template:read",
    TemplateWrite = "template:write",
    TenantAddMember = "tenant:add-member",
    TenantListMembers = "tenant:list-members",
    TenantRemoveMember = "tenant:remove-member",
    TenantWrite = "tenant:write",
}

export const permissions: ReadonlyArray<string> = Object.keys(Permission).map(key => Permission[key as any]);
